---
- name: Hello World!
  hosts: localhost
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Ansible is working."

  - name: Install ntp
    yum: name=ntp state=present
    notify: enable service ntp

  - name: Start ntp
    service: name=ntpd state=started

  - name: Identify old system release
    shell: echo "Old system, consider upgrading {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version|int < 5


