---
- name: Deploy Hello World
  hosts: localhost
  connection: local
 
  tasks:
 
  - name: Verifying Parameters
    meta: noop

  - name: "Removing {{ ns }}"
    debug: 
      msg: "{{ true }}"
    when: delete == "Yes"

  - name: "Creating {{ ns }}"
    debug: 
      msg: "K8s namespace {{ ns }} created successfully"

  - name: "Deploying into {{ ns }}/{{ env}}"
    debug: 
      msg: "Hello world deployed to {{ ns }}/{{ env }} in 150ms"

