---
- name: Deploy Hello World
  hosts: localhost
  connection: local
 
  tasks:
 
  - name: Verifying Parameters
    meta: noop

  - name: "Removing {{ ns }}"
    debug: 
      msg: "{{ true }}"
    when: delete == "Yes"

  - name: "Creating {{ ns }}"
    meta: noop

  - name: "Deploying into {{ ns }}/{{ env}}"
    meta: noop

