---
- name: install and start ntp
  hosts: tag_Name_node

  tasks:
  - name: stop ntp
    service: name=ntpd state=stopped
    ignore_errors: true

  - name: remove ntp
    yum: pkg=ntp state=absent

