---
- name: Delegated Service Management
  hosts: all
  vars:
    in_scope: False

  tasks:
  - name: Member groups
    debug:
      msg: "{{ group_names }}"

  - name: Confirm host scope
    set_fact:
      in_scope:  True
    when: group_scope | intersect(group_names)

  - name: Apply Patches
    debug: msg="{{ True }}"
    changed_when: True
    when: apply_patches and in_scope

  - name: Restart apache
    debug: msg="{{ True }}"
    changed_when: True
    when: service_restart and in_scope

  - name: Reboot Server
    debug: msg="{{ True }}"
    changed_when: True
    when: server_restart and in_scope


