---
- name: Delegated Service Management
  hosts: all

  tasks:
  - name: Select groups
    debug: msg="{{ group_scope }}"

  - name: Apply Patches
    debug: msg="{{ True }}"
    when: apply_patches is True

  - name: Restart apache
    debug: msg="{{ True }}"
    when: service_restart

  - name: Reboot Server
    debug: msg="{{ True }}"
    when: server_restart


